### ISSUE TITLE
querystring.unescape is not a function

### ISSUE THREAD

**Issue by Gargron** [jhermsmeier/node-http-link-header#10]
In Link.parseAttrs

I looked up the querystring module and it seems like "unescape" is not a thing, "decode" is https://github.com/Gozala/querystring/blob/master/index.js

But now looking at your package.json I don't see it included, so perhaps this is an issue from running this module in the browser instead of in Node.

**Comment by jhermsmeier** [comment]
The querystring module used in here is not https://github.com/Gozala/querystring – it's Node's builtin querystring module: https://nodejs.org/api/querystring.html – which is why it doesn't show up in the `package.json`.

How are you running it in the browser? With browserify?

**Comment by Gargron** [comment]
Yes! I am surprised it didn't throw any errors about `require('querystring')` going nowhere, but I don't know how the internals of that work. Considering extracting this lib's functionality into my main app where I can edit it for a quick fix.

**Comment by jhermsmeier** [comment]
But browserify should include the Node querystring API when bundling it – did you happen to install the `querystring` module from Gozala manually (that would result in it being loaded instead)?

**Comment by Gargron** [comment]
No, I did not! (Although if one of the other deps installed it, I wouldn't know it)

For the record, this whole situation happens when one of the links in the Link header contains a URL like `http://localhost:3000/api/v1/notifications?exclude_types%5B%5D=follow&exclude_types%5B%5D=favourite&max_id=2`

**Comment by Gargron** [comment]
I have intercepted the `parseAttrs` function call with monkey patching and from inspecting what `import querystring from 'querystring'` returns, it is indeed that Gozala library.

**Comment by Gargron** [comment]
Alright, I have basically copypasted the parseAttr function into my own code, replacing the original one (thankfully they're all exposed and not private) and replacing `querystring.unescape` with `querystring.decode` seems to have fixed it.

**Comment by jhermsmeier** [comment]
Okay, sounds very much like there's something going on with your dependency tree – I'll do a browserify test with this later, to check what's happening.

**Comment by jhermsmeier** [comment]
@Gargron did you figure out what ultimately caused this? And does it work without patching the method now?
