### ISSUE TITLE
rel and anchor should not be escaped

### ISSUE THREAD

**Issue by dtomas** [jhermsmeier/node-http-link-header#13]
The values in rel/anchor should not get URL-escaped, as they may/must contain URIs/URI references.
(See https://tools.ietf.org/html/rfc5988#section-5.2 and https://tools.ietf.org/html/rfc5988#section-5.3.)

**Comment by jhermsmeier** [comment]
Oh yes, I've missed this – thanks for bringing it up!

**Comment by evert** [comment]
Neither does `type`. I'm getting this as a result:

    </foo>; rel=alternate; type="application%2Fhal%2Bjson"

**Comment by jhermsmeier** [comment]
Thanks @evert @dtomas! This should be fixed in v1.0.0 now

**Comment by evert** [comment]
Thank you!
