### ISSUE TITLE
Link.has(attr, value) always returns true

### ISSUE THREAD

**Issue by greengiraffe** [jhermsmeier/node-http-link-header#14]
### Problem
`Link.has('someattr', 'somevalue')` always returns true, even if `'someattr'` and `'somevalue'` are not present in link header.

### Technical description
This is what `Link.has(attr, value)` ([Line #101](https://github.com/jhermsmeier/node-http-link-header/blob/master/lib/link.js#L101)) looks like:

```js
has( attr, value ) {
  return this.get( attr, value ) != null
}
```
It checks if `Link.get(attr, value)` returned `null`.

`Link.get(attr, value)` ([Line #83](https://github.com/jhermsmeier/node-http-link-header/blob/master/lib/link.js#L83)) **always** returns an Array, **never** `null`. In case the provided attr/value pair is not present, an empty array is returned. An empty array is truthy and not `null`, thus `Link.has` always returns `true`.

### Solution

Either change `Link.has` to check for `this.get( attr, value ).length` or update `Link.get` to return null when the array is empty. I tend to prefer the latter, because then the returned value is falsy.

**Comment by jhermsmeier** [comment]
Thanks! Fix published in `http-link-header@1.0.1`

**Comment by dhui** [comment]
Checking the length of the array seems like a cleaner solution to me. That way, the return type for `get()` is always an Array.

We could also speed up `has()` in the friendly case. e.g. `has()` has it's own implementation and breaking out of the search if an `attr` with the given `value` is found. It'd save a bit of memory as well.

**Comment by jhermsmeier** [comment]
@dhui feel free to send a PR :)
