### ISSUE TITLE
ref storage

### ISSUE THREAD

**Issue by dhui** [jhermsmeier/node-http-link-header#19]
We can improve the performance of ref lookups by using a [map](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map)
> The Map object holds key-value pairs and remembers the original insertion order of the keys. Any value (both objects and primitive values) may be used as either a key or a value.

**Comment by jhermsmeier** [comment]
I did use a `Map` in this when I first wrote it, but couldn't see any noticeable performance improvement, and it made the API a bit clunkier to work with.
But there's the very real benefit of not having unclean input tainting language specific object keys, so I'm happy to use a `Map` instead.
