### ISSUE TITLE
Error on link header with `nopush`

### ISSUE THREAD

**Issue by adamraine** [jhermsmeier/node-http-link-header#29]
Downstream bug: https://github.com/GoogleChrome/lighthouse/issues/14934

The `parse` function throws a `Expected attribute delimiter at offset 94` when `nopush` is in a link header. `nopush` should be valid syntax here.

Repro script:

```js
import LinkHeader from 'http-link-header';

const headerValue = '<https://assets.calendly.com/assets/booking/css/booking-d0ac32b1.css>; rel=preload; as=style; nopush';
const refs = LinkHeader.parse(headerValue);
```

**Comment by lasseschou** [comment]
And if there are other types of issues (I just had a `Link:` HTTP header starting with a double-quote) the parser should handle it gracefully, adding a warning to the audit, or failing the audit. It shouldn't leave the SEO score at zero.

**Comment by lnfel** [comment]
Was going nuts on pagespeed insights because of the errors, turns out the issue was not on our code. When using sveltekit adapter-node it generates link headers such as the following which is causes the same error as the OP mentioned:
```
link: <./_app/immutable/assets/_layout.0a91e5b9.css>; rel="preload";as="style"; nopush, <./_app/immutable/assets/_page.add9dcec.css>; rel="preload";as="style"; nopush, <./_app/immutable/entry/start.ed0ae258.js>; rel="modulepreload"; nopush, <./_app/immutable/chunks/index.917e459a.js>; rel="modulepreload"; nopush, <./_app/immutable/chunks/singletons.e239e713.js>; rel="modulepreload"; nopush, <./_app/immutable/chunks/parse.d12b0d5b.js>; rel="modulepreload"; nopush, <./_app/immutable/entry/app.eb870153.js>; rel="modulepreload"; nopush, <./_app/immutable/entry/_layout.svelte.ff05d707.js>; rel="modulepreload"; nopush, <./_app/immutable/entry/_page.svelte.f156ed39.js>; rel="modulepreload"; nopush, <./_app/immutable/chunks/stores.78032b0e.js>; rel="modulepreload"; nopush
```
